name: EG-pr
concurrency:
  group: eg-pr-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
           
  call-rwf:
    needs: prepare-context
    uses: ./.github/workflows/rw.yaml
    with:
      publish: true
